with-expecter: True
dir: "./mocks"
mockname: "{{.InterfaceName}}"
outpkg: "mocks"
filename: "{{.InterfaceName}}.go"
all: True
packages:
  github.com/rimvydascivilis/book-tracker/backend/domain:
    config:
      recursive: True
