name: Backend CI

on:
  pull_request:
    paths:
      - "backend/**"
  push:
    paths:
      - "backend/**"
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.x'
      - name: Install dependencies
        run: |
          cd ${{ github.workspace }}/backend
          make install-deps
      - name: Lint
        run: |
          cd ${{ github.workspace }}/backend
          make lint
      - name: Build
        run: |
          cd ${{ github.workspace }}/backend
          make build
      - name: Test
        run: |
          cd ${{ github.workspace }}/backend
          make tests
