name: Backend CI

on:
  pull_request:
    paths:
      - "backend/**"
  push:
    paths:
      - "backend/**"
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.x'

      - name: Lint
        uses: golangci/golangci-lint-action@v6
      - name: Build
        run: go build ./cmd/server/main.go
      - name: Test with the Go CLI
        run: go test ./...
